[build]
builder = "nixpacks"
buildCommand = "npm install --omit=dev"

[deploy]
startCommand = "node dist/index.mjs"
healthcheckPath = "/api/healthz"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
